// app/layout.tsx
// import { ThemeFetcher } from "@/lib/client-theme-provider"
import { Toaster } from "@/components/ui/sonner";
import { ThemeFetcher } from "@/lib/color-fetcher";
import { Providers } from "@/lib/providers";
import "./globals.css";
// import { ThemeFetcher } from "@/lib/ThemeFetcher"
import AuthProvider from "@/components/provider/AuthProvider";
import { CrispProvider } from "@/provider/crisp-provider";
import { Manrope } from "next/font/google";
import { cookies } from "next/headers";

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const primaryColor = cookieStore.get("themeColor")?.value || "black";

  return (
    <html lang="en">
      <head>
        <style>{`:root { --primary: ${primaryColor}; }`}</style>
      </head>
      <body className={`${manrope.variable} antialiased`}>
        <AuthProvider>
          <Providers>
            <ThemeFetcher />
            {children}
            <Toaster />
            <CrispProvider />
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
