// app/layout.tsx
// import { ThemeFetcher } from "@/lib/client-theme-provider"
import { ThemeFetcher } from "@/lib/color-fetcher"
import "./globals.css"
import { Toaster } from "@/components/ui/sonner"
import { Providers } from "@/lib/providers"
// import { ThemeFetcher } from "@/lib/ThemeFetcher"
import { Manrope } from "next/font/google"
import { cookies } from "next/headers"

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookieStore = cookies()
  const primaryColor = cookieStore.get("themeColor")?.value || "black"

  return (
    <html lang="en">
      <head>
        <style>{`:root { --primary: ${primaryColor}; }`}</style>
      </head>
      <body className={`${manrope.variable} antialiased bg-[#F8FEFF]`}>
        <Providers>
          <ThemeFetcher />
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  )
}
